### ISSUE TITLE
Updating a macro throws exception

### ISSUE THREAD

**Issue by Prodeguerriero** [facetoe/zenpy#209]
Hi there.

First off, thanks for the great work. I am using zenpy extensively and it proves to be useful on a daily basis.

Now, to the problem. I am trying to download some macros, edit them and update Zendesk with the changes.

No matter what I try to do, I get an exception thrown at me. It appears as something might be going wrong with the conversion to JSON, but I am not sure. I even tried to simply download a macro and upload it again, but it still happens. Here is a snipped of the code

```python
my_macro = zenpy_client.macros(id=123456789)
    for action in my_macro.actions:
        print(my_macro.id, my_macro.title, action.field, action.value)
        try:
            updated_macro = zenpy_client.macros.update(my_macro)
        except:
            print("Whopsie. Did not update.")
```

Attached you'll find the exception log.

Thanks!

[exception.txt](https://github.com/facetoe/zenpy/files/1863583/exception.txt)

**Comment by facetoe** [comment]
The code above fails as the macro object has not been modified and so it only sends the id to Zendesk, which for some reason causes it to fail:

You can see how the object will be serialized as follows:

```python
print(macro.to_dict(serialize=True))
```

If I modify the object, I don't receive any error:

```python
macro = zenpy_client.macros(id=360014933232)
macro.title = 'I AM TEST'
print(macro.to_dict(serialize=True))
zenpy_client.macros.update(macro)
```

Does the code above work for you or do you still get the exception?

**Comment by Prodeguerriero** [comment]
Yup, editing the `title` attribute works fine. Actions are still giving me e headache, which was brought me to editing macros in the first place.

If I try the code below, the update succeeds because of the change to `title`, but `action.value` does not change. 

```python
 my_macro = zenpy_client.macros(id=360000828866)
    my_macro.title = ("Test macro " + str(random.randrange(100)))    
    
    for action in my_macro.actions:
        if action.field == "group_id":
            print(vars(action))
            action.value = "21471916"
            print(vars(action))
        try:
            print(my_macro.to_dict(serialize=True))
            updated_macro = zenpy_client.macros.update(my_macro)
        except:
            print("Whopsie. Did not update.")
```

The serialization results in the following:
```
{'id': 360000828866, 'title': 'Test macro [XX]'}
```

**Comment by facetoe** [comment]
OK I guess I missed the case where an object is modified while it is being iterated over. I've fixed this now. I have a few other bits and pieces to do and then I'll push a new version to Pypy. 

Thanks for the report!

**Comment by facetoe** [comment]
I've pushed a new version to Pypy.

**Comment by Prodeguerriero** [comment]
Hi there,

Thanks for pushing the update. I just gave it a shot, but it still fails.
The serialization shows the action, so that appears to work, but the raised exception is now different:

```
{'actions': [Action()], 'id': 360000828866, 'title': 'Test macro 56'}
Whopsie. Did not update.
Traceback (most recent call last):
  File "zendesk_testing_template.py", line 65, in <module>
    main()
  File "zendesk_testing_template.py", line 58, in main
    updated_macro = zenpy_client.macros.update(my_macro)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zenpy/lib/api.py", line 423, in update
    return CRUDRequest(self).put(api_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zenpy/lib/request.py", line 99, in put
    return self.api._put(url, payload=payload)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zenpy/lib/api.py", line 90, in _put
    response = self._call_api(self.session.put, url, json=self._serialize(payload), timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zenpy/lib/api.py", line 135, in _call_api
    self._check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zenpy/lib/api.py", line 274, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": "RecordInvalid", "description": "Record validation errors", "details": {"actions": [{"description": "Actions: cannot be blank", "error": "BlankValue"}]}}
```
If I print `vars(action)` before and after updating action.value, I get the following.
Before
`{'_dirty_attributes': {'_dirty_callback'}, '_dirty_callback': <function ProxyList._wrap_element.<locals>.dirty_callback at 0x104116730>, 'api': <zenpy.lib.api.MacroApi object at 0x10420f2b0>, 'field': 'group_id', 'value': '21582736'}`
After
`{'_dirty_attributes': {'value', '_dirty_callback'}, '_dirty_callback': <function ProxyList._wrap_element.<locals>.dirty_callback at 0x104116730>, 'api': <zenpy.lib.api.MacroApi object at 0x10420f2b0>, 'field': 'group_id', 'value': '24096186'}`

Hope this helps.

**Comment by facetoe** [comment]
Gah, alright I've really fixed the bug now. Actions are now dicts and no longer objects. You can update an action like so:

```python
macro = zenpy_client.macros(id=360015276352)
macro.actions[0]['value'] = "I am a new value"
zenpy_client.macros.update(macro)
```

Let me know if this works for you and I'll push a new version.

**Comment by Prodeguerriero** [comment]
Almost there!

If I use
```python
print(my_macro.actions)
print(my_macro.actions[0]["value"])
my_macro.actions[0]["value"]='24096186'
print(my_macro.actions[1]["value"])
my_macro.actions[1]["value"]='pending'

print(my_macro.to_dict(serialize=True))
```
the stdout is
```
[{'field': 'group_id', 'value': '21582736'}, {'field': 'status', 'value': 'open'}]
21582736
open
{'actions': [{'field': 'group_id', 'value': '24096186'}, {'field': 'status', 'value': 'pending'}], 'id': 360000828866, 'title': 'Test macro 79'}
```
and everything is updated as expected.

If I iterate instead
```python
for action in my_macro.actions:
    if action['field'] == "group_id":
        print(action['value'])
        action['value'] = "24096186"
        print(action['value'])
    elif action['field'] == 'status':
        print(action['value'])
        action['value']= 'solved'
        print(action['value'])
print(my_macro.actions[0]["value"])
print(my_macro.actions[1]["value"])

print(my_macro.to_dict(serialize=True))
```
the stdout is
```
21582736
24096186
open
solved
21582736
open
{'actions': [{'field': 'group_id', 'value': '21582736'}, {'field': 'status', 'value': 'open'}], 'id': 360000828866, 'title': 'Test macro 89'}
```
and only the title is updated, as the serialization shows.

I honestly have no clue why the values don't seem to stick once the for loop is exited.

Back to you :)

**Comment by Prodeguerriero** [comment]
Success!
Editing actions or removing them works as expected now. :)

Thanks much.

P.S. you should add a donation button ;)

**Comment by Prodeguerriero** [comment]
I think I bumped into a similar problem with the restriction settings. I don't know it's worth marking a different issue, though, as it seem awfully similar to the previous issue.

Using the following:
```python
my_macro = zenpy_client.macros(id=33635659)
print(my_macro.to_dict(serialize=True))
print("Restriction: {}".format(my_macro.restriction))
my_macro.restriction = None
my_macro.title = "New title"
print(my_macro.to_dict(serialize=True))
print("Restriction: {}".format(my_macro.restriction))
```
here is what I get in return.
```
{'id': 33635659}
Restriction: {'type': 'Group', 'id': 21704903, 'ids': [21704903]}
{'id': 33635659, 'title': 'New title'}
Restriction: None
```
The serialization doesn't seem to pick up the change in the `restriction` attribute. If I try to update (without changing the title) I get the same exception I was originally complaining about.

Sorry :(

**Comment by facetoe** [comment]
Zenpy doesn't send attributes that are `None` to Zendesk, so at first I thought that was the issue. I tried changing your code as follows:

```python
macro = zenpy_client.macros(id=360015276352)
macro.restrictions = {}
print(macro.to_dict(serialize=True))
```

And it outputs:

```
{'restrictions': {}, 'id': 360015276352}
```

However still throws the exception. I thought that was a bit funny so tried making the request with curl:

```
curl -v -u 'email:password' https://domain.zendesk.com/api/v2/macros/360015276352.json   -H "Content-Type: application/json" -X PUT -d '{"macro": {"restrictions": {}}}'
```

It still throws a 400. Looking through the curl output I noticed this strange line:

```
< X-Zendesk-API-Warn: Removed restricted keys ["macro.restrictions"] from parameters according to whitelist
```

After a bit of digging I discovered that the correct attribute name is `restriction`, and that is why it is failing. Now I am able to set the restriction to null via curl, however if I try to set it to an empty dict I get a 500 internal server error.

I've patched Zenpy to allow sending `None` to Zendesk as the original reason for preventing it no longer applies after adding the incremental update feature. I can now update my macro without any errors.

Can you confirm that it is working for you also?

And don't be sorry for submitting bug reports, if I know about them at least I can fix them!

**Comment by facetoe** [comment]
Ahh I just noticed that the `restrictions` typo was mine. Oh well, that was a fun trip down debugging lane all the same.

**Comment by Prodeguerriero** [comment]
Sorry, haven't had the chance to test it yet.
I'll give it a shot asap.

Thanks!

**Comment by Prodeguerriero** [comment]
I confirm that I can now update the macros as expected. I did observe one thing that might be worth mentioning.
If use the code
```python
macro=zenpy_client.macros(id=49471956)
print(macro.to_dict(serialize=True))
macro.restriction = None
print(macro.to_dict(serialize=True))
```
I get in return
```
{'id': 49471956}
{'id': 49471956, 'restriction': None}
```
Which is what one would expect.

If I use
```python
macros = zenpy_client.macros(active=True)
    for macro in macros:
        if (macro.restriction and
                macro.restriction['type'] == 'Group' and
                macro.id == 49471956):
            print(macro.to_dict(serialize=True))
            macro.restriction = None
            print(macro.to_dict(serialize=True))
```
I then get
```
{'id': 49471956, 'restriction': {'type': 'Group', 'id': 21582736, 'ids': [21582736]}}
{'id': 49471956, 'restriction': None}
```

Note that if I change the condition of the if clause to only `macro.id == 49471956` the serialization output goes back to normal.

On a side note, quick question. I understand that passing different values to attributes of the top level endpoints allows filtering. For example `macros(Active=True)` returns a generator with only active macros and `macros(id=xxxxx)` returns one specific macro object.
By looking at the [API Objects docs](http://docs.facetoe.com.au/api_objects.html#zenpy.lib.api_objects.Macro) it would seem as if I should be able to use `restriction` as well, but I was not successful. Passing `restriction=True` or `restriction=False` yield the exact same result, which is the same I get when passing nothing. Where am I going wrong?

Thanks!

**Comment by facetoe** [comment]
OK I've fixed up that weirdness and will push a new version soon. With the other question, when you call `macros(<kwargs>)` the arguments are processed by an Endpoint, in this case the MacroEndpoint, which will format the parameters and send them of to Zendesk. In this case the API call executed is https://developer.zendesk.com/rest_api/docs/core/macros#list-macros, so any of the parameters listed in the docs there should work. Zendesk does add parameters and API calls reasonably regularly so it is possible that a particular parameter is not supported in Zenpy yet, but generally speaking they should be.

The documentation here could definitely be improved.
